language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: kgzzRZQ2i019rrbIpjonFw4sMS/vpl8zWNb9ibow6iJVpDf473jZgNC8/uCAiLrioaEFgO9q4fi/VsZPgozXdqWy8xH4xtMJmm1S3a99rQKLPLH5dYQ+stFKTAFYeHzMPsujkh+qauJOc18/E4Z9YlqHmCc0FFBkFMkoO362u/Xh5toicKD5hiERmWpLL+sHFYgtpDZoxW5nhEhBEq64LVI0CWAZZoI+hmIpvcZNkqRa2umEd0xZw+2zEZZ9+nM1RdezqvnqLczi9g2vjDt0U/jhaUKnjIUer/0+xeuJUZKADSHoM6jODnPGu7YTVd0aNmbIEJ7WGwKArR+YDhpxel/optfNm3AAAPT27MCxPQRzMO55fiTynhD66BjScjCV2xdM5SW0ZfXvZDx3Sn70INGfjh42ImiTH9gzKmaz0o7/va397XmuBboQYLKCrs+w7NY/MiUkbbxKDymD2PgzMGM1Zrwu/2qZ4y4h5lZcD3U5fILrqudCKq+P6Q/Pn8glnaLriEJyQfxscV2mVzLzn3wYl5OlpJ/YjY4y2WGglMSWncmme18VE8AyEy5BW+WiBYcOkjWGq14Ah9lBHIkkquNUbZi/HPp2pMbK59Y98AP6yHObO9teB00/oN9dFOKALC5P1DfPN18NY2WzMBzkA9e436iALkcwB0tmuFk+9m0=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-core
    all_branches: true
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
