language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: a791HWDGjPJJGfqRLm4jaj80D3NWMgbn/qU3lZ92rK0CGsnMeuN1eO9EckhuwV+dh/XD4bLOib3hwsSBe4xW/S17JqklQxN1bcX5FQD06eahd3YFe1t1iCq/Efv2Ry27msryZyY6Bwko8IyHMLYSnX9p5IMooJFDWhj8Qrn3TVdgtqj93ZLOhIY0502LvzxsdKnre1zYJa7UmXGaQTA57n4SawAfbejPClL6yyqQidIK4bBsSpsOqerRodCmIbn91JgIUg1NDtfOLRBuH5r7gqIJml0XiFOXgMuzZvnUmbQZM2U8rYKdqngWRwAKYeeKnlMKSuOK1Vgbut8QvRh5zRcdx0qEA7AzZbuQSWzLFwPMZbWRjbV2CuwwtFGkOYjWotTKFs6XE319JPYOoVct2sppqfvqyq/Qm42dV3NYQq6kcgko6M4lVtOg/GmtaiyaNUoRCOR5RlIgiLlR/DlCfUmfqrMlv5t+B31yYXYPTtTNiWH2ZpTlv4N0LIgpmNV4DmYOg0ZGa9Cta+Xb3SKwH3MSORCZbOZGC188TnBC0M5LVrjESEVp3OGra1IAlKUAiqHS6vY8aMC1YNN5aOYTjCaIEwgiEFXgcm9b+DeMFefk1/PsDzzZ9Rf3RzPgXs36z2fF5J/IJz7z7WtPkj2OE57r4nBIIZXcSeoxzAh+jyQ=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-core
    all_branches: true
branches:
  only:
  - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
