language: node_js
node_js: '8'
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: FyVt4HzjSrGYC27RnTIirNZzVs/cE+UzaBEK2petPiz6DHfoDexIQOgWNJcWw392UKnQfmkVOf/A865f1+tAiZQsdtVfq7bUZVMopVSe428MeMcJ6Hb76RAvJ3nA0l+yQfegiDxmgQhbsQC09heI+OHIZlaHKW7ijb/eP4+LcXL6jq9mbRfvINtUrhdpUAuw4lg0cd/R04kxylkf/yWMPIrZZ+ZyXsGnSsIHVvhQted3P321rkxO3byUn5g2nBbbX3ndikCPitlCFvQwwF2kMZS5K4KXBSx6zEWxxs9tzHkyhjYEGu1NrLR0jOkPDaCer3bfnLX+rZ/tsTBmsuvBx6VRCirPQ6Q1n7gb4ojRRWK38LQ8GD/959/Pd78p36qAF/8TiQQGWWpzH2tWUQNeOjAJ7fEGJoL1jDvy6J9j5hDsqlDuJWNzqxzjD7QTyeRfqynLIuXsi72FzsU1W5giEZCdYAETUPb98SJeU5NvtDc953APQnRSUZ+qDT4Y2RmDLi+yVpKtp2cjzwfOu2zButBDwjeNiaZvGlry/nIfhlDYfqLS4uLw2tU2f0zxg8Ue9AoXHX9ke/3rsYzvItMsDpJiai5HdjxukD9X2CMTijAZFF23ijmrpc1xcvDuJgun+NP+vHIMGctjqtDJjt2yNvfoeGHc4SkFCbug9XTrNYM=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-core
    all_branches: true

branches:
  only:
    - /^release\/\d+\.\d+\.\d+$/
